name: Build Core

on:
  push:
    branches:
      - develop
    paths: 
      - '**.js'
      - '**.json'
      - '**.css'
      - '!dist/**'
      - '!cypress/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        uses: Borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - name: Build Core
        uses: Borales/actions-yarn@v2.0.0
        with:
          cmd: build:core # will run `yarn build:core` command
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v2.2.0
        with:
          commit_message: Update engine core
          branch: develop
          file_pattern: dist/engine/core
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
